# Generated by Django 3.2.8 on 2021-10-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_rename_nombre_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=150)),
                ('account_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='authApp.account')),
                ('destiny_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny', to='authApp.account')),
            ],
        ),
    ]
